name: Codecoverage

# Runs codeception unit and wpunit tests, merges the code coverage, commits the html report to
# GitHub Pages, generates a README badge with the coverage percentage.

# Automatically creates the gh-pages branch but it needs to be manually enabled in the repository settings.

on:
  push:
    branches:
      - master

jobs:

  codecoverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: bh_wp_plugin_updater_tests
        ports:
          - 65019:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        php: [ '8.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check does gh-pages branch need to be created
        run: |
          git checkout origin/gh-pages || true;
          if [[ $(git branch -l gh-pages) == "" ]]; then
            gh_pages_branch_needed=true
          else
            gh_pages_branch_needed=false
          fi
          echo "GH_PAGES_BRANCH_NEEDED=$gh_pages_branch_needed" >> $GITHUB_ENV;
          mkdir gh-pages || true;

      - name:  Maybe create gh-pages branch
        if: ${{ env.GH_PAGES_BRANCH_NEEDED }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
          force_orphan: true
          allow_empty_commit: true
          commit_message: "🤖 Creating gh-pages branch"

      - name: Checkout GitHub Pages branch for code coverage report
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: composer
          extensions: zip

      - name: Read .env.testing
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env.testing

      - name: Run composer install
        continue-on-error: true
        run: composer install

      - name: Allow writing to wp-content
        run: sudo chmod -R a+w wp-content

      - name: Clear previous code coverage
        run: |
          rm -rf gh-pages/phpunit || true;
          mkdir gh-pages/phpunit || true;

      - name: Run unit tests
        run: XDEBUG_MODE=coverage vendor/bin/codecept run unit --coverage ./tests/_output/unit.cov --debug || true;

      - name: Run wpunit tests
        run: XDEBUG_MODE=coverage vendor/bin/codecept run wpunit --coverage ./tests/_output/wpunit.cov --debug || true;

      - name: Merge code coverage
        run: vendor/bin/phpcov merge --clover tests/_output/clover.xml --php ./gh-pages/phpunit/phpunit.cov --html gh-pages/phpunit/html/ ./tests/_output/;

      # See: https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
      - name: Add `.nojekyll` file so code coverage report successfully deploys to gh-pages
        working-directory: gh-pages/phpunit
        run: |
          touch .nojekyll
          git add -- .nojekyll *

      - name: Update README badge
        run: vendor/bin/php-coverage-badger tests/_output/clover.xml gh-pages/phpunit/coverage.svg PHPUnit

      - name: Commit code coverage to gh-pages
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: gh-pages
          branch: gh-pages
          commit_message: "🤖 Save code coverage report to gh-pages" # TODO: include the percentage change in the message.
          commit_options: ""
        env:
          GITHUB_TOKEN: "${{ github.token }}"